name: Push to Replicate

on:
  push:
    branches:
      - master  # Workflow akan berjalan otomatis pada branch 'main'
      #test
jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
      # # Step 1: Install NVIDIA drivers
      # - name: Install NVIDIA drivers
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y software-properties-common
      #     sudo add-apt-repository -y ppa:graphics-drivers/ppa
      #     sudo apt-get update
      #     sudo apt-get install -y nvidia-driver-525  # Ganti dengan versi driver yang sesuai
      #     sudo modprobe nvidia  # Mengaktifkan driver NVIDIA tanpa reboot

      # # Step 2: Install CUDA Toolkit
      # - name: Install CUDA Toolkit
      #   run: |
      #     wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
      #     sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
      #     sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
      #     sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
      #     sudo apt-get update
      #     sudo apt-get install -y cuda-11-7  # Ganti dengan versi CUDA yang sesuai

      # # Step 3: Verify GPU and CUDA installation
      # - name: Verify NVIDIA GPU and CUDA
      #   run: |
      #     nvidia-smi
      #     nvcc --version
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Prepare Lora Model
        working-directory: src/dawetAI/workflow/replicate
        run: |
          # Check and remove existing lora_model directory
          if [ -d "lora_model" ]; then
            echo "Found existing lora_model directory. Removing..."
            rm -rf lora_model
          fi

          # Download the model
          echo "Downloading model..."
          wget -q https://files.catbox.moe/ujxa6r.zip

          # Extract the model
          echo "Extracting model..."
          unzip -q ujxa6r.zip -d lora_model

          # Remove the zip file
          echo "Cleaning up zip file..."
          rm -f ujxa6r.zip

      - name: Push to Replicate
        working-directory: src/dawetAI/workflow/replicate
        run: |
          cog push r8.im/abdanhafidz/dawet-ai
